services:
  emqx:
    build: .
    container_name: emqx_container

    ports:
      - "8883:8883"
      - "18083:18083"

    volumes:
      - ./docker_vol/emqx_data:/opt/emqx/data
      - ./docker_vol/emqx_log:/opt/emqx/log
      - ./emqx_setup/certs:/opt/emqx/etc/certs:ro

    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=0.0.0.0

      # TLS
      - EMQX_LISTENERS__SSL__DEFAULT__BIND=8883

      - EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CACERTFILE=/opt/emqx/etc/certs/ca_chain.pem
      - EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CERTFILE=/opt/emqx/etc/certs/fullchain18-5.pem
      - EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__KEYFILE=/opt/emqx/etc/certs/mqttserver18-05.pem
      # - EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CERTFILE=/opt/emqx/etc/certs/MQTTbroker18-5-26REVOKEDCHAIN.pem
      # - EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__KEYFILE=/opt/emqx/etc/certs/mqttserver18-05REVOKED.pem

      # mTLS
      - EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__VERIFY=verify_peer
      - EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__FAIL_IF_NO_PEER_CERT=true

      # TLS versions
      - EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__VERSIONS=[tlsv1.2,tlsv1.3]
      - EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CIPHERS=["ECDHE-ECDSA-AES256-GCM-SHA384","ECDHE-ECDSA-AES128-GCM-SHA256","TLS_AES_256_GCM_SHA384","TLS_CHACHA20_POLY1305_SHA256"]


      # CRL AUTO FETCH
      - EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__ENABLE_CRL_CHECK=true
      #- EMQX_LISTENERS__SSL__DEFAULT__MAX_PACKET_SIZE=1KB

      # CRL cache
      - EMQX_CRL_CACHE__HTTP_TIMEOUT=15s
      - EMQX_CRL_CACHE__CAPACITY=100
      - EMQX_CRL_CACHE__REFRESH_INTERVAL=15m

      # message limits
      # - EMQX_MQTT__MAX_PACKET_SIZE=1KB
      - EMQX_MQTT__MAX_PACKET_SIZE=1KB
      - EMQX_LISTENERS__SSL__DEFAULT__MESSAGES_RATE=20/s
      - EMQX_LISTENERS__SSL__DEFAULT__MESSAGES_BURST=40/s
      
      # flapping detection
      - EMQX_FLAPPING_DETECT__ENABLE=true
      - EMQX_FLAPPING_DETECT__MAX_COUNT=15
      - EMQX_FLAPPING_DETECT__WINDOW_TIME=1m
      - EMQX_FLAPPING_DETECT__BAN_TIME=5m
      # dashboard
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=public

      # disable others
      - EMQX_LISTENERS__WSS__DEFAULT__ENABLE=false
      - EMQX_LISTENERS__WS__DEFAULT__ENABLE=false
      - EMQX_LISTENERS__TCP__DEFAULT__ENABLE=false

    restart: unless-stopped

    networks:
      - emqx-net

networks:
  emqx-net:
    driver: bridge